Don't return error when execute "portstat -d"
If execute "portstat -d" without execute "portstat" first,
then this command would fail due to "No such file or directory"

Before fix:
root@as5812-54x:/home/admin# portstat -d
Traceback (most recent call last):
  File "/usr/bin/portstat", line 411, in <module>
    main()
  File "/usr/bin/portstat", line 355, in main
    if os.listdir(cnstat_dir) == []:
OSError: [Errno 2] No such file or directory: '/tmp/portstat-0'

Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>