Handling error scenario of adding port to Vlan which is part of LAG
Signed-off-by: Sudharsan Dhamal Gopalarathnam <sudharsand@nvidia.com>
Handled error scenario when adding a port to Vlan which is already part
of a LAG

Fixed the config vlan script to check if port is a port channel member
before setting config_db

config vlan add 10
config portchannel add PortChannel0
config portchannel member add PortChannel0 Ethernet0
config vlan member add 10 Ethernet0

Usage: config vlan member add [OPTIONS] <vid> port
Try "config vlan member add -h" for help.

Error: Ethernet0 is part of portchannel!